import { AgentCoordinatorService } from './AgentCoordinatorService';
import { DeepSeekModelService } from '../DeepSeek_AI_Services/DeepSeekModelService';
import Logger from '../../utils/Logger/Logger';

// فایلە پێویستە سەرەکییەکان
const REQUIRED_FILES_TEMPLATES = {
    'pubspec.yaml': (name: string) => `name: ${name}\ndescription: Generated by 20X AI Agent.\nversion: 1.0.0+1\n\nenvironment:\n  sdk: '>=3.0.0 <4.0.0'\n\ndependencies:\n  flutter:\n    sdk: flutter\n`,
    'android/build.gradle': `// Android build configuration generated by AI Agent`,
    'ios/Podfile': `# iOS configuration generated by AI Agent`,
    // ... هتد بۆ فایلەکانی تر
};

export class ProjectInitializerService {
    private deepSeekService: DeepSeekModelService;
    private coordinatorService: AgentCoordinatorService;

    constructor() {
        this.deepSeekService = new DeepSeekModelService();
        this.coordinatorService = AgentCoordinatorService.getInstance();
    }

    /**
     * @function initializeProjectFromPartialCode
     * دروستکردنی تەواوی پێکهاتەی پڕۆژە لەسەر بنەمای کۆدێکی ناتەواو (وەک تەنها فۆڵدەری lib)
     */
    public async initializeProjectFromPartialCode(projectId: string, projectName: string, existingFiles: string[]): Promise<void> {
        Logger.info(`Initializer Agent: Starting full project setup for ${projectName} (${projectId}).`);

        const filesToCreate: { path: string, content: string }[] = [];

        // 1. دروستکردنی فایلە پێویستەکان بە Template
        for (const [path, templateFnOrString] of Object.entries(REQUIRED_FILES_TEMPLATES)) {
            const content = typeof templateFnOrString === 'function' ? templateFnOrString(projectName) : templateFnOrString;
            filesToCreate.push({ path, content });
        }

        // 2. داواکردن لە DeepSeek بۆ دروستکردنی فایلەکان
        const deepSeekPrompt = `Generate all necessary boilerplate code for a standard Flutter project named '${projectName}'. Focus on correct settings for 'android/build.gradle' and 'ios/Podfile'. Also ensure correct dependencies based on the existing Dart files: ${existingFiles.join(', ')}. Return the content in JSON format: [{"path": "...", "content": "..."}].`;

        const aiResponse = await this.deepSeekService.getAICompletion({
            prompt: deepSeekPrompt,
            context: `Creating Flutter project files for ${projectName}`,
            modelName: 'DeepSeek-V2', 
        });

        try {
            // شیکارکردنی وەڵامی AI (JSON)
            const aiGeneratedFiles = JSON.parse(aiResponse.result);
            filesToCreate.push(...aiGeneratedFiles);
        } catch (e) {
            Logger.error('Initializer Agent failed to parse DeepSeek response.', e);
        }

        // 3. ناردنی ئەرک بۆ File System Agent بۆ نووسینی فایلەکان
        await this.coordinatorService.assignTask({
            taskId: `INIT_${Date.now()}`,
            agentId: 'INITIALIZER_AGENT', 
            taskType: 'WRITE_FILES_BATCH',
            projectPath: projectId,
            priority: 'HIGH',
            details: { files: filesToCreate, description: `Auto-generated all missing Flutter project files.` }
        } as unknown as any);

        Logger.info(`Initializer Agent: Successfully queued ${filesToCreate.length} files for creation.`);

        // Socket.io.emit('projectUpdate', { projectId, message: 'Full project structure initialized by AI Agent.' });
    }
}
